services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - C:/Downloads/jpa/Database:/var/lib/postgresql/data
    ports:
      - "5432:5432"